GROQ_MODEL_CLASSIFY = "llama-3.1-8b-instant"
GROQ_MODEL_PARSE_INVOICE = "llama-3.1-8b-instant"
GROQ_MODEL_PARSE_PO = "llama-3.1-8b-instant"
GROQ_MODEL_CONFIDENCE = "llama-3.1-8b-instant"

CLASSIFICATION_TEXT_LIMIT = 1500
LOW_CONFIDENCE_THRESHOLD = 70.0
