GROQ_MODEL_CLASSIFY = "qwen/qwen3.6-27b"
GROQ_MODEL_EXTRACTION = "qwen/qwen3.6-27b"
GROQ_MODEL_PARSE_INVOICE = "qwen/qwen3.6-27b"
GROQ_MODEL_PARSE_PO = "qwen/qwen3.6-27b"

CLASSIFICATION_TEXT_LIMIT = 1500
LOW_CONFIDENCE_THRESHOLD = 80.0
