GROQ_MODEL_VISION = "qwen/qwen3.6-27b"
GROQ_MODEL_CLASSIFY = "qwen/qwen3.6-27b"
GROQ_MODEL_EXTRACTION = GROQ_MODEL_VISION
GROQ_MODEL_PARSE_INVOICE = "llama-3.3-70b-versatile"
GROQ_MODEL_PARSE_PO = "llama-3.3-70b-versatile"
GROQ_MODEL_CONFIDENCE = "llama-3.3-70b-versatile"

GEMINI_MODEL_EXTRACTION = "gemini-2.5-flash"

CLASSIFICATION_TEXT_LIMIT = 1500
INVOICE_EXTRACTION_MAX_PDF_PAGES = 2
LOW_CONFIDENCE_THRESHOLD = 80.0
PDF_MIN_USABLE_TEXT_CHARS = 80
PDF_MIN_USABLE_TEXT_RATIO = 0.3
